name: Compile COBOL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GnuCOBOL
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol

      - name: Compile COBOL Program
        run: cobc -x hello.cob -o hello.out

      - name: Verify build output
        run: ls -l

      - name: Run Program
        run: |
          chmod +x hello.out
          ./hello.out
